### ISSUE TITLE
Making a website for this

### ISSUE THREAD

**Issue by kylecoburn** [genkimarshall/wwwild#9]
Just some ideas on this. Curious as to where you're aiming to go from here.

* Email/phone number only login (confirm via code on subsequent logins)
* Syncs your saved feed sources and items (clients fetch and cache actual content on demand)
* WebKit extension (easily abstracted for Chrome/Safari)
 * Notifies you when your feeds become available, shows a badged button of unread items in the toolbar, and links you straight to where you left off on the feeds pages
 * Doesn't _require_ user to install the extension, but gets the integration advantages when they choose to
* Mobile versions?

**Comment by genkimarshall** [comment]
Awesome, thanks for starting this.
I'll get back to bouncing off the individual ideas, at a cursory glance I'm 100% with them :)

I think it's also be good to kick this off really quickly, so that it can get solidified/expanded:

#### Staying with extension - cons
* No mobile version
* Closed to only Chrome users

#### Staying with extension - pros
* Less friction to get started with it (though email only login is very friction-less admittedly. And likely having an account would likely be desired even with an extension, so that people can save their subscriptions - which would be especially crucial if/when this thing were to extend to beyond subreddits - see #2)
* Less development time (though this is debatable probably)

**Comment by kylecoburn** [comment]
The good thing is all the work from the extension would either remain as an extension for the final product, or transfer almost directly over (js/html) to a website version.

It depends on the person, but for some, installing an extension is a bigger barrier than signing up for an account. Regardless, I definitely think it's smart to have a Chrome extension that can promote itself on the store, and embed a new-user onboarding workflow, so visiting the homepage itself is never _required_.

**Comment by genkimarshall** [comment]
Yeah, well put.
As for extension installation friction, that's fair, i could definitely see that being the case.
I guess after earlier discussions about providing it for anyone, I have currently been in a little rut, seeing basically you, Dylan, and I as the target audience.
In the midst of writing this comment I feel like I have come out of that shell a little bit. A website really does make more sense.
Okay, with that in mind, thoughts on what development stack to use? Yes, there was that old Rails app implementation, but I want to re-examine this question..

Also, I feel obligated to bring this up now. Keeping mobile in mind while making a website is awesome, and I love it when websites do. But if it ever is a website that I'm interacting with on a consistent basis on my phone, I immediately wish it was just an app, no matter how well it is done.. I can't help but get rid of that nagging thought. What's your reaction?

**Comment by kylecoburn** [comment]
Ideally yeah it would have native apps for Android and iOS, and there's never an easy answer for that. But creating a responsive version of the website, as a starting point, has almost no additional overhead.

By keeping the use case tightly focused, a "reader" app for it should be a reasonable scope. There's undoubtedly cool stuff with a native app that would benefit from (push notifications, cache new content in the background so it's ready to read on the subway, etc). I'd imagine a lot of people would consume it primarily from mobile.

If there's a server backend for it anyway, a website shouldn't differ significantly in the amount of work vs a Chrome extension (either way you're writing a version of the UI in html/js).

Development stack would really be up to you. There are lots of well suited options, Rails included, so it's really down to what you'll be most comfortable working in (admittedly not the easiest question to answer with foresight).

**Comment by genkimarshall** [comment]
[this has been / is being resolved offline] :D

**Comment by kylecoburn** [comment]
Onward and upward!
